
title: âˆšgrace #Your awesome title
email: db3p@naver.com #youremail@domain.com
description: > # this means to ignore newlines until "baseurl"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of the site
url: "https://db3ppp.github.io/" # the base hostname & protocol for your site

permalink: /:year-:month/:title
timezone:

favicon: /assets/img/icon.png

google_analytics: #UAâ€”XXXXXXXX-X
disqus_shortname: db3ppp-github-io#disqus shortname

user:
  name: Hyewon Kim
  pic: /assets/img/profile.png
  picAlt: "catbook"
  job: undergraduate in CSğŸ‘©ğŸ»â€ğŸ’»
  aboutme: true # comment this out if you don't need the 'about' page.

exclude:
  - LICENSE
  - github

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comment: true   

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown 

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false
